//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools2.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory.
        /// </summary>
        internal static string Accessory {
            get {
                return ResourceManager.GetString("Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_c0101a{0}_{1}_{2}.mtrl.
        /// </summary>
        internal static string AccMtrlFile {
            get {
                return ResourceManager.GetString("AccMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/accessory/a{0}/material/v.
        /// </summary>
        internal static string AccMtrlFolder {
            get {
                return ResourceManager.GetString("AccMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au Ra.
        /// </summary>
        internal static string Au_Ra {
            get {
                return ResourceManager.GetString("Au_Ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop Autoturret.
        /// </summary>
        internal static string Bishop_Autoturret {
            get {
                return ResourceManager.GetString("Bishop_Autoturret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Hands.
        /// </summary>
        internal static string Body_Hands {
            get {
                return ResourceManager.GetString("Body_Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Hands + Legs.
        /// </summary>
        internal static string Body_Hands_Legs {
            get {
                return ResourceManager.GetString("Body_Hands_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Hands + Legs + Feet.
        /// </summary>
        internal static string Body_Hands_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Hands_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body + Legs + Feet.
        /// </summary>
        internal static string Body_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_c{0}b{1}_a.mtrl.
        /// </summary>
        internal static string BodyMtrlFile {
            get {
                return ResourceManager.GetString("BodyMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/human/c{0}/obj/body/b{1}/material.
        /// </summary>
        internal static string BodyMtrlFolder {
            get {
                return ResourceManager.GetString("BodyMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbuncle.
        /// </summary>
        internal static string Carbuncle {
            get {
                return ResourceManager.GetString("Carbuncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorSet.
        /// </summary>
        internal static string ColorSet {
            get {
                return ResourceManager.GetString("ColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_d{0}e{1}_{2}_a.mtrl.
        /// </summary>
        internal static string DemiMtrlFile {
            get {
                return ResourceManager.GetString("DemiMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/demihuman/d{0}/obj/equipment/e{1}/material/v.
        /// </summary>
        internal static string DemiMtrlFolder {
            get {
                return ResourceManager.GetString("DemiMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse.
        /// </summary>
        internal static string Diffuse {
            get {
                return ResourceManager.GetString("Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ears.
        /// </summary>
        internal static string Ears {
            get {
                return ResourceManager.GetString("Ears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elezen.
        /// </summary>
        internal static string Elezen {
            get {
                return ResourceManager.GetString("Elezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eos.
        /// </summary>
        internal static string Eos {
            get {
                return ResourceManager.GetString("Eos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -decal_{0}.tex.
        /// </summary>
        internal static string EquipDecalFile {
            get {
                return ResourceManager.GetString("EquipDecalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/common/texture/decal_equip.
        /// </summary>
        internal static string EquipDecalFolder {
            get {
                return ResourceManager.GetString("EquipDecalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Decals.
        /// </summary>
        internal static string Equipment_Decals {
            get {
                return ResourceManager.GetString("Equipment_Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_c{0}e{1}_{2}_{3}.mtrl.
        /// </summary>
        internal static string EquipMtrlFile {
            get {
                return ResourceManager.GetString("EquipMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/equipment/e{0}/material/v.
        /// </summary>
        internal static string EquipMtrlFolder {
            get {
                return ResourceManager.GetString("EquipMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Error.
        /// </summary>
        internal static string Error_DirectoryError {
            get {
                return ResourceManager.GetString("Error_DirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find file, please check your directories under settings.
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etc.
        /// </summary>
        internal static string Etc {
            get {
                return ResourceManager.GetString("Etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exd.
        /// </summary>
        internal static string ExdFolder {
            get {
                return ResourceManager.GetString("ExdFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        internal static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint.
        /// </summary>
        internal static string Face_Paint {
            get {
                return ResourceManager.GetString("Face_Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_c{0}f{1}_{2}_a.mtrl.
        /// </summary>
        internal static string FaceMtrlFile {
            get {
                return ResourceManager.GetString("FaceMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/human/c{0}/obj/face/f{1}/material.
        /// </summary>
        internal static string FaceMtrlFolder {
            get {
                return ResourceManager.GetString("FaceMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _decal_{0}.tex.
        /// </summary>
        internal static string FacePaintFile {
            get {
                return ResourceManager.GetString("FacePaintFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/common/texture/decal_face.
        /// </summary>
        internal static string FacePaintFolder {
            get {
                return ResourceManager.GetString("FacePaintFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garuda Egi.
        /// </summary>
        internal static string Garuda_Egi {
            get {
                return ResourceManager.GetString("Garuda_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        internal static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_c{0}h{1}_{2}_{3}.mtrl.
        /// </summary>
        internal static string HairMtrlFile {
            get {
                return ResourceManager.GetString("HairMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/human/c{0}/obj/hair/h{1}/material/v0001.
        /// </summary>
        internal static string HairMtrlFolder {
            get {
                return ResourceManager.GetString("HairMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head + Body.
        /// </summary>
        internal static string Head_Body {
            get {
                return ResourceManager.GetString("Head_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyur Highlander.
        /// </summary>
        internal static string Hyur_H {
            get {
                return ResourceManager.GetString("Hyur_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyur Midlander.
        /// </summary>
        internal static string Hyur_M {
            get {
                return ResourceManager.GetString("Hyur_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ifrit Egi.
        /// </summary>
        internal static string Ifrit_Egi {
            get {
                return ResourceManager.GetString("Ifrit_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iris.
        /// </summary>
        internal static string Iris {
            get {
                return ResourceManager.GetString("Iris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item_{0}_{1}.exd.
        /// </summary>
        internal static string itemFile {
            get {
                return ResourceManager.GetString("itemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lalafell.
        /// </summary>
        internal static string Lalafell {
            get {
                return ResourceManager.GetString("Lalafell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language requires the application to restart. \nRestart now?.
        /// </summary>
        internal static string Language_Change {
            get {
                return ResourceManager.GetString("Language_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language requires the application to restart. \nRestart now?.
        /// </summary>
        internal static string Language_Change_En {
            get {
                return ResourceManager.GetString("Language_Change_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs + Feet.
        /// </summary>
        internal static string Legs_Feet {
            get {
                return ResourceManager.GetString("Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Hand.
        /// </summary>
        internal static string Main_Hand {
            get {
                return ResourceManager.GetString("Main_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Hand + Off Hand.
        /// </summary>
        internal static string Main_Off {
            get {
                return ResourceManager.GetString("Main_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companion_0_{0}.exd.
        /// </summary>
        internal static string MinionFile {
            get {
                return ResourceManager.GetString("MinionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minions.
        /// </summary>
        internal static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqote.
        /// </summary>
        internal static string Miqote {
            get {
                return ResourceManager.GetString("Miqote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modelchara_0.exd.
        /// </summary>
        internal static string ModelCharaFile {
            get {
                return ResourceManager.GetString("ModelCharaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_m{0}b{1}_{2}.mtrl.
        /// </summary>
        internal static string MonsterMtrlFile {
            get {
                return ResourceManager.GetString("MonsterMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/monster/m{0}/obj/body/b{1}/material/v.
        /// </summary>
        internal static string MonsterMtrlFolder {
            get {
                return ResourceManager.GetString("MonsterMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mount_0_{0}.exd.
        /// </summary>
        internal static string MountFile {
            get {
                return ResourceManager.GetString("MountFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Hand.
        /// </summary>
        internal static string Off_Hand {
            get {
                return ResourceManager.GetString("Off_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramuh Egi.
        /// </summary>
        internal static string Ramuh_Egi {
            get {
                return ResourceManager.GetString("Ramuh_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rings.
        /// </summary>
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roegadyn.
        /// </summary>
        internal static string Roegadyn {
            get {
                return ResourceManager.GetString("Roegadyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook Autoturret.
        /// </summary>
        internal static string Rook_Autoturret {
            get {
                return ResourceManager.GetString("Rook_Autoturret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Textures.
        /// </summary>
        internal static string SearchBox {
            get {
                return ResourceManager.GetString("SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selene.
        /// </summary>
        internal static string Selene {
            get {
                return ResourceManager.GetString("Selene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        internal static string Skin {
            get {
                return ResourceManager.GetString("Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Crystal.
        /// </summary>
        internal static string Soul_Crystal {
            get {
                return ResourceManager.GetString("Soul_Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular.
        /// </summary>
        internal static string Specular {
            get {
                return ResourceManager.GetString("Specular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail.
        /// </summary>
        internal static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_c{0}t{1}_a.mtrl.
        /// </summary>
        internal static string TailMtrlFile {
            get {
                return ResourceManager.GetString("TailMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/human/c{0}/obj/tail/t{1}/material.
        /// </summary>
        internal static string TailMtrlFolder {
            get {
                return ResourceManager.GetString("TailMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titan Egi.
        /// </summary>
        internal static string Titan_Egi {
            get {
                return ResourceManager.GetString("Titan_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Handed.
        /// </summary>
        internal static string Two_Handed {
            get {
                return ResourceManager.GetString("Two_Handed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt_w{0}b{1}_{2}.mtrl.
        /// </summary>
        internal static string WeapMtrlFile {
            get {
                return ResourceManager.GetString("WeapMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chara/weapon/w{0}/obj/body/b{1}/material/v.
        /// </summary>
        internal static string WeapMtrlFolder {
            get {
                return ResourceManager.GetString("WeapMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrists.
        /// </summary>
        internal static string Wrists {
            get {
                return ResourceManager.GetString("Wrists", resourceCulture);
            }
        }
    }
}
