//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_TexTools2.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_TexTools2.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory 的本地化字符串。
        /// </summary>
        public static string Accessory {
            get {
                return ResourceManager.GetString("Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 a{0}.imc 的本地化字符串。
        /// </summary>
        public static string AccIMCFile {
            get {
                return ResourceManager.GetString("AccIMCFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/accessory/a{0} 的本地化字符串。
        /// </summary>
        public static string AccIMCFolder {
            get {
                return ResourceManager.GetString("AccIMCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c{0}a{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string AccMDLFile {
            get {
                return ResourceManager.GetString("AccMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/accessory/a{0}/model 的本地化字符串。
        /// </summary>
        public static string AccMDLFolder {
            get {
                return ResourceManager.GetString("AccMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_c{0}a{1}_{2}_{3}.mtrl 的本地化字符串。
        /// </summary>
        public static string AccMtrlFile {
            get {
                return ResourceManager.GetString("AccMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/accessory/a{0}/material/v 的本地化字符串。
        /// </summary>
        public static string AccMtrlFolder {
            get {
                return ResourceManager.GetString("AccMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 action_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 actioncategory_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string ActionCategory {
            get {
                return ResourceManager.GetString("ActionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add/Remove: 的本地化字符串。
        /// </summary>
        public static string Add_Remove {
            get {
                return ResourceManager.GetString("Add_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Mesh 的本地化字符串。
        /// </summary>
        public static string AddMesh {
            get {
                return ResourceManager.GetString("AddMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Part 的本地化字符串。
        /// </summary>
        public static string AddPart {
            get {
                return ResourceManager.GetString("AddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *Note: These options are still in development and may not work properly. 的本地化字符串。
        /// </summary>
        public static string AdvImportNote {
            get {
                return ResourceManager.GetString("AdvImportNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALL 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt Fix 的本地化字符串。
        /// </summary>
        public static string Attempt_Fix {
            get {
                return ResourceManager.GetString("Attempt_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use these options if the item has holes appear when combined with other items. 的本地化字符串。
        /// </summary>
        public static string AttemptFixText {
            get {
                return ResourceManager.GetString("AttemptFixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attributes: 的本地化字符串。
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Au Ra 的本地化字符串。
        /// </summary>
        public static string Au_Ra {
            get {
                return ResourceManager.GetString("Au_Ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Au Ra Raen 的本地化字符串。
        /// </summary>
        public static string AuRa_Raen {
            get {
                return ResourceManager.GetString("AuRa_Raen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Au Ra Xaela 的本地化字符串。
        /// </summary>
        public static string AuRa_Xaela {
            get {
                return ResourceManager.GetString("AuRa_Xaela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autodesk Collada 的本地化字符串。
        /// </summary>
        public static string AutodeskCollada {
            get {
                return ResourceManager.GetString("AutodeskCollada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bahamut-Egi 的本地化字符串。
        /// </summary>
        public static string Bahamut_Egi {
            get {
                return ResourceManager.GetString("Bahamut_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beneficial 的本地化字符串。
        /// </summary>
        public static string Beneficial {
            get {
                return ResourceManager.GetString("Beneficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bishop Autoturret 的本地化字符串。
        /// </summary>
        public static string Bishop_Autoturret {
            get {
                return ResourceManager.GetString("Bishop_Autoturret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Hands 的本地化字符串。
        /// </summary>
        public static string Body_Hands {
            get {
                return ResourceManager.GetString("Body_Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Hands + Legs 的本地化字符串。
        /// </summary>
        public static string Body_Hands_Legs {
            get {
                return ResourceManager.GetString("Body_Hands_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Hands + Legs + Feet 的本地化字符串。
        /// </summary>
        public static string Body_Hands_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Hands_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body + Legs + Feet 的本地化字符串。
        /// </summary>
        public static string Body_Legs_Feet {
            get {
                return ResourceManager.GetString("Body_Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c{0}b{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string BodyMDLFile {
            get {
                return ResourceManager.GetString("BodyMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/body/b{1}/model 的本地化字符串。
        /// </summary>
        public static string BodyMDLFolder {
            get {
                return ResourceManager.GetString("BodyMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_c{0}b{1}_a.mtrl 的本地化字符串。
        /// </summary>
        public static string BodyMtrlFile {
            get {
                return ResourceManager.GetString("BodyMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/body/b{1}/material 的本地化字符串。
        /// </summary>
        public static string BodyMtrlFolder {
            get {
                return ResourceManager.GetString("BodyMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bone addition is automatic 的本地化字符串。
        /// </summary>
        public static string Bone_addition_is_automatic {
            get {
                return ResourceManager.GetString("Bone_addition_is_automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bones: 的本地化字符串。
        /// </summary>
        public static string Bones {
            get {
                return ResourceManager.GetString("Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buddy 的本地化字符串。
        /// </summary>
        public static string Buddy {
            get {
                return ResourceManager.GetString("Buddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 buddyaction_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string BuddyAction {
            get {
                return ResourceManager.GetString("BuddyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carbuncle 的本地化字符串。
        /// </summary>
        public static string Carbuncle {
            get {
                return ResourceManager.GetString("Carbuncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Selected 的本地化字符串。
        /// </summary>
        public static string Clear_Selected {
            get {
                return ResourceManager.GetString("Clear_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorSet 的本地化字符串。
        /// </summary>
        public static string ColorSet {
            get {
                return ResourceManager.GetString("ColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Companions 的本地化字符串。
        /// </summary>
        public static string Companions {
            get {
                return ResourceManager.GetString("Companions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company 的本地化字符串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 companyaction_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string CompanyAction {
            get {
                return ResourceManager.GetString("CompanyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count: 的本地化字符串。
        /// </summary>
        public static string Count_colon {
            get {
                return ResourceManager.GetString("Count_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Craft 的本地化字符串。
        /// </summary>
        public static string Craft {
            get {
                return ResourceManager.GetString("Craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 craftaction_100000_{0}.exd 的本地化字符串。
        /// </summary>
        public static string CraftAction {
            get {
                return ResourceManager.GetString("CraftAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make XML 的本地化字符串。
        /// </summary>
        public static string CreateXML {
            get {
                return ResourceManager.GetString("CreateXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DemiHuman 的本地化字符串。
        /// </summary>
        public static string DemiHuman {
            get {
                return ResourceManager.GetString("DemiHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e{0}.imc 的本地化字符串。
        /// </summary>
        public static string DemiIMCFile {
            get {
                return ResourceManager.GetString("DemiIMCFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/demihuman/d{0}/obj/equipment/e{1} 的本地化字符串。
        /// </summary>
        public static string DemiIMCFolder {
            get {
                return ResourceManager.GetString("DemiIMCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 d{0}e{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string DemiMDLFile {
            get {
                return ResourceManager.GetString("DemiMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/demihuman/d{0}/obj/equipment/e{1}/model 的本地化字符串。
        /// </summary>
        public static string DemiMDLFolder {
            get {
                return ResourceManager.GetString("DemiMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_d{0}e{1}_{2}_{3}.mtrl 的本地化字符串。
        /// </summary>
        public static string DemiMtrlFile {
            get {
                return ResourceManager.GetString("DemiMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/demihuman/d{0}/obj/equipment/e{1}/material/v 的本地化字符串。
        /// </summary>
        public static string DemiMtrlFolder {
            get {
                return ResourceManager.GetString("DemiMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 skl_d{0}b{1}.sklb 的本地化字符串。
        /// </summary>
        public static string DemiSkelFile {
            get {
                return ResourceManager.GetString("DemiSkelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/demihuman/d{0}/skeleton/base/b{1} 的本地化字符串。
        /// </summary>
        public static string DemiSkelFolder {
            get {
                return ResourceManager.GetString("DemiSkelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detrimental 的本地化字符串。
        /// </summary>
        public static string Detrimental {
            get {
                return ResourceManager.GetString("Detrimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diffuse 的本地化字符串。
        /// </summary>
        public static string Diffuse {
            get {
                return ResourceManager.GetString("Diffuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directories 的本地化字符串。
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Extra Data 的本地化字符串。
        /// </summary>
        public static string Disable_Extra_Data {
            get {
                return ResourceManager.GetString("Disable_Extra_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DX Version 的本地化字符串。
        /// </summary>
        public static string DX_Version {
            get {
                return ResourceManager.GetString("DX_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DX11 的本地化字符串。
        /// </summary>
        public static string DX11 {
            get {
                return ResourceManager.GetString("DX11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DX9 的本地化字符串。
        /// </summary>
        public static string DX9 {
            get {
                return ResourceManager.GetString("DX9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ears 的本地化字符串。
        /// </summary>
        public static string Ears {
            get {
                return ResourceManager.GetString("Ears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elezen 的本地化字符串。
        /// </summary>
        public static string Elezen {
            get {
                return ResourceManager.GetString("Elezen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emote 的本地化字符串。
        /// </summary>
        public static string Emote {
            get {
                return ResourceManager.GetString("Emote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 emote_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string EmoteEXD {
            get {
                return ResourceManager.GetString("EmoteEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable 的本地化字符串。
        /// </summary>
        public static string Enable_Disable {
            get {
                return ResourceManager.GetString("Enable_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eos 的本地化字符串。
        /// </summary>
        public static string Eos {
            get {
                return ResourceManager.GetString("Eos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -decal_{0}.tex 的本地化字符串。
        /// </summary>
        public static string EquipDecalFile {
            get {
                return ResourceManager.GetString("EquipDecalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/common/texture/decal_equip 的本地化字符串。
        /// </summary>
        public static string EquipDecalFolder {
            get {
                return ResourceManager.GetString("EquipDecalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e{0}.imc 的本地化字符串。
        /// </summary>
        public static string EquipIMCFile {
            get {
                return ResourceManager.GetString("EquipIMCFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/equipment/e{0} 的本地化字符串。
        /// </summary>
        public static string EquipIMCFolder {
            get {
                return ResourceManager.GetString("EquipIMCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c{0}e{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string EquipMDLFile {
            get {
                return ResourceManager.GetString("EquipMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/equipment/e{0}/model 的本地化字符串。
        /// </summary>
        public static string EquipMDLFolder {
            get {
                return ResourceManager.GetString("EquipMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment 的本地化字符串。
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Decals 的本地化字符串。
        /// </summary>
        public static string Equipment_Decals {
            get {
                return ResourceManager.GetString("Equipment_Decals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_c{0}e{1}_{2}_{3}.mtrl 的本地化字符串。
        /// </summary>
        public static string EquipMtrlFile {
            get {
                return ResourceManager.GetString("EquipMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/equipment/e{0}/material/v 的本地化字符串。
        /// </summary>
        public static string EquipMtrlFolder {
            get {
                return ResourceManager.GetString("EquipMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 skl_c{0}{1}{2}.sklb 的本地化字符串。
        /// </summary>
        public static string EquipSkelFile {
            get {
                return ResourceManager.GetString("EquipSkelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/skeleton/{1}/{2}{3} 的本地化字符串。
        /// </summary>
        public static string EquipSkelFolder {
            get {
                return ResourceManager.GetString("EquipSkelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ve{0}.avfx 的本地化字符串。
        /// </summary>
        public static string EquipVFXFile {
            get {
                return ResourceManager.GetString("EquipVFXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/equipment/e{0}/vfx/eff 的本地化字符串。
        /// </summary>
        public static string EquipVFXFolder {
            get {
                return ResourceManager.GetString("EquipVFXFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory Error 的本地化字符串。
        /// </summary>
        public static string Error_DirectoryError {
            get {
                return ResourceManager.GetString("Error_DirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find file, please check your directories under settings 的本地化字符串。
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Etc 的本地化字符串。
        /// </summary>
        public static string Etc {
            get {
                return ResourceManager.GetString("Etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eventaction_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string EventAction {
            get {
                return ResourceManager.GetString("EventAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0a0000 的本地化字符串。
        /// </summary>
        public static string EXDDat {
            get {
                return ResourceManager.GetString("EXDDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exd 的本地化字符串。
        /// </summary>
        public static string ExdFolder {
            get {
                return ResourceManager.GetString("ExdFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Existing 的本地化字符串。
        /// </summary>
        public static string Existing {
            get {
                return ResourceManager.GetString("Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export as DDS 的本地化字符串。
        /// </summary>
        public static string Export_as_DDS {
            get {
                return ResourceManager.GetString("Export_as_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export as Image 的本地化字符串。
        /// </summary>
        public static string Export_as_Image {
            get {
                return ResourceManager.GetString("Export_as_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Model + Materials 的本地化字符串。
        /// </summary>
        public static string exportObjButton {
            get {
                return ResourceManager.GetString("exportObjButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Mesh Data: 的本地化字符串。
        /// </summary>
        public static string ExtraMeshData {
            get {
                return ResourceManager.GetString("ExtraMeshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face 的本地化字符串。
        /// </summary>
        public static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face Paint 的本地化字符串。
        /// </summary>
        public static string Face_Paint {
            get {
                return ResourceManager.GetString("Face_Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c{0}f{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string FaceMDLFile {
            get {
                return ResourceManager.GetString("FaceMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/face/f{1}/model 的本地化字符串。
        /// </summary>
        public static string FaceMDLFolder {
            get {
                return ResourceManager.GetString("FaceMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_c{0}f{1}_{2}_{3}.mtrl 的本地化字符串。
        /// </summary>
        public static string FaceMtrlFile {
            get {
                return ResourceManager.GetString("FaceMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/face/f{1}/material 的本地化字符串。
        /// </summary>
        public static string FaceMtrlFolder {
            get {
                return ResourceManager.GetString("FaceMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _decal_{0}.tex 的本地化字符串。
        /// </summary>
        public static string FacePaintFile {
            get {
                return ResourceManager.GetString("FacePaintFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/common/texture/decal_face 的本地化字符串。
        /// </summary>
        public static string FacePaintFolder {
            get {
                return ResourceManager.GetString("FacePaintFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feet 的本地化字符串。
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFXIV Directory 的本地化字符串。
        /// </summary>
        public static string FFXIV_Directory {
            get {
                return ResourceManager.GetString("FFXIV_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Marker 的本地化字符串。
        /// </summary>
        public static string FieldMarker {
            get {
                return ResourceManager.GetString("FieldMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fieldmarker_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string FieldMarkerEXD {
            get {
                return ResourceManager.GetString("FieldMarkerEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food 的本地化字符串。
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Garuda-Egi 的本地化字符串。
        /// </summary>
        public static string Garuda_Egi {
            get {
                return ResourceManager.GetString("Garuda_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gear 的本地化字符串。
        /// </summary>
        public static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 generalaction_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string GeneralAction {
            get {
                return ResourceManager.GetString("GeneralAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hair 的本地化字符串。
        /// </summary>
        public static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c{0}h{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string HairMDLFile {
            get {
                return ResourceManager.GetString("HairMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/hair/h{1}/model 的本地化字符串。
        /// </summary>
        public static string HairMDLFolder {
            get {
                return ResourceManager.GetString("HairMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_c{0}h{1}_{2}_{3}.mtrl 的本地化字符串。
        /// </summary>
        public static string HairMtrlFile {
            get {
                return ResourceManager.GetString("HairMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/hair/h{1}/material/v0001 的本地化字符串。
        /// </summary>
        public static string HairMtrlFolder {
            get {
                return ResourceManager.GetString("HairMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hands 的本地化字符串。
        /// </summary>
        public static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head 的本地化字符串。
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head + Body 的本地化字符串。
        /// </summary>
        public static string Head_Body {
            get {
                return ResourceManager.GetString("Head_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyur Highlander 的本地化字符串。
        /// </summary>
        public static string Hyur_H {
            get {
                return ResourceManager.GetString("Hyur_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyur Midlander 的本地化字符串。
        /// </summary>
        public static string Hyur_M {
            get {
                return ResourceManager.GetString("Hyur_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon ID 的本地化字符串。
        /// </summary>
        public static string Icon_ID {
            get {
                return ResourceManager.GetString("Icon_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ui/icon/{0} 的本地化字符串。
        /// </summary>
        public static string IconFolder {
            get {
                return ResourceManager.GetString("IconFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ui/icon/{0}/hq 的本地化字符串。
        /// </summary>
        public static string IconHQFolder {
            get {
                return ResourceManager.GetString("IconHQFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ui/icon/{0}/{1} 的本地化字符串。
        /// </summary>
        public static string IconLangFolder {
            get {
                return ResourceManager.GetString("IconLangFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ifrit-Egi 的本地化字符串。
        /// </summary>
        public static string Ifrit_Egi {
            get {
                return ResourceManager.GetString("Ifrit_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing File 的本地化字符串。
        /// </summary>
        public static string Importing_File {
            get {
                return ResourceManager.GetString("Importing_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No index file backups detected. \nWould you like to create a backup now? \n\nWarning: This will disable any active modifications in order to create a backup. They will have to be manually re-enabled. 的本地化字符串。
        /// </summary>
        public static string Index_Backup {
            get {
                return ResourceManager.GetString("Index_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index Backups Directory 的本地化字符串。
        /// </summary>
        public static string Index_Backups_Directory {
            get {
                return ResourceManager.GetString("Index_Backups_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Iris 的本地化字符串。
        /// </summary>
        public static string Iris {
            get {
                return ResourceManager.GetString("Iris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item List 的本地化字符串。
        /// </summary>
        public static string Item_List {
            get {
                return ResourceManager.GetString("Item_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 item_{0}_{1}.exd 的本地化字符串。
        /// </summary>
        public static string itemFile {
            get {
                return ResourceManager.GetString("itemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items 的本地化字符串。
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 040000 的本地化字符串。
        /// </summary>
        public static string ItemsDat {
            get {
                return ResourceManager.GetString("ItemsDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 itemuicategory_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string ItemUICategory {
            get {
                return ResourceManager.GetString("ItemUICategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join us on Discord! 的本地化字符串。
        /// </summary>
        public static string Join_us_on_Discord {
            get {
                return ResourceManager.GetString("Join_us_on_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lalafell 的本地化字符串。
        /// </summary>
        public static string Lalafell {
            get {
                return ResourceManager.GetString("Lalafell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the language requires the application to restart. \nRestart now? 的本地化字符串。
        /// </summary>
        public static string Language_Change {
            get {
                return ResourceManager.GetString("Language_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the language requires the application to restart. \nRestart now? 的本地化字符串。
        /// </summary>
        public static string Language_Change_En {
            get {
                return ResourceManager.GetString("Language_Change_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legs 的本地化字符串。
        /// </summary>
        public static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legs + Feet 的本地化字符串。
        /// </summary>
        public static string Legs_Feet {
            get {
                return ResourceManager.GetString("Legs_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lighting 的本地化字符串。
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -nowloading_base{0}.tex 的本地化字符串。
        /// </summary>
        public static string LoadingImage {
            get {
                return ResourceManager.GetString("LoadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Hand 的本地化字符串。
        /// </summary>
        public static string Main_Hand {
            get {
                return ResourceManager.GetString("Main_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Hand + Off Hand 的本地化字符串。
        /// </summary>
        public static string Main_Off {
            get {
                return ResourceManager.GetString("Main_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 map_0.exd 的本地化字符串。
        /// </summary>
        public static string MapExd {
            get {
                return ResourceManager.GetString("MapExd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}_{1}.tex 的本地化字符串。
        /// </summary>
        public static string MapFile1 {
            get {
                return ResourceManager.GetString("MapFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}d.tex 的本地化字符串。
        /// </summary>
        public static string MapFile2 {
            get {
                return ResourceManager.GetString("MapFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}m_{1}.tex 的本地化字符串。
        /// </summary>
        public static string MapFile3 {
            get {
                return ResourceManager.GetString("MapFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ui/map/{0} 的本地化字符串。
        /// </summary>
        public static string MapFolder {
            get {
                return ResourceManager.GetString("MapFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maps 的本地化字符串。
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Symbols 的本地化字符串。
        /// </summary>
        public static string MapSymbol {
            get {
                return ResourceManager.GetString("MapSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marker 的本地化字符串。
        /// </summary>
        public static string Marker {
            get {
                return ResourceManager.GetString("Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 marker_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string MarkerEXD {
            get {
                return ResourceManager.GetString("MarkerEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mask 的本地化字符串。
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material: 的本地化字符串。
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Materials: 的本地化字符串。
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFXIV TexTools 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Bug 的本地化字符串。
        /// </summary>
        public static string Menu_BugReport {
            get {
                return ResourceManager.GetString("Menu_BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize 的本地化字符串。
        /// </summary>
        public static string Menu_Customize {
            get {
                return ResourceManager.GetString("Menu_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directories 的本地化字符串。
        /// </summary>
        public static string Menu_Directories {
            get {
                return ResourceManager.GetString("Menu_Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Menu_English {
            get {
                return ResourceManager.GetString("Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Settings 的本地化字符串。
        /// </summary>
        public static string Menu_ExportSettings {
            get {
                return ResourceManager.GetString("Menu_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        public static string Menu_French {
            get {
                return ResourceManager.GetString("Menu_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        public static string Menu_German {
            get {
                return ResourceManager.GetString("Menu_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Modpack 的本地化字符串。
        /// </summary>
        public static string Menu_ImportModpack {
            get {
                return ResourceManager.GetString("Menu_ImportModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        public static string Menu_Japanese {
            get {
                return ResourceManager.GetString("Menu_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make ModPack 的本地化字符串。
        /// </summary>
        public static string Menu_MakeModpack {
            get {
                return ResourceManager.GetString("Menu_MakeModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod List 的本地化字符串。
        /// </summary>
        public static string Menu_ModList {
            get {
                return ResourceManager.GetString("Menu_ModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check For Problems 的本地化字符串。
        /// </summary>
        public static string Menu_ProblemCheck {
            get {
                return ResourceManager.GetString("Menu_ProblemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-enable All Mods 的本地化字符串。
        /// </summary>
        public static string Menu_ReapplyAll {
            get {
                return ResourceManager.GetString("Menu_ReapplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable All Mods 的本地化字符串。
        /// </summary>
        public static string Menu_RevertAll {
            get {
                return ResourceManager.GetString("Menu_RevertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Over 的本地化字符串。
        /// </summary>
        public static string Menu_StartOver {
            get {
                return ResourceManager.GetString("Menu_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tutorials 的本地化字符串。
        /// </summary>
        public static string Menu_Tutorials {
            get {
                return ResourceManager.GetString("Menu_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mesh: 的本地化字符串。
        /// </summary>
        public static string Mesh {
            get {
                return ResourceManager.GetString("Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meshes: 的本地化字符串。
        /// </summary>
        public static string MeshCount {
            get {
                return ResourceManager.GetString("MeshCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24 的本地化字符串。
        /// </summary>
        public static string Minion_Category {
            get {
                return ResourceManager.GetString("Minion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 companion_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string MinionFile {
            get {
                return ResourceManager.GetString("MinionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minions 的本地化字符串。
        /// </summary>
        public static string Minions {
            get {
                return ResourceManager.GetString("Minions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miqote 的本地化字符串。
        /// </summary>
        public static string Miqote {
            get {
                return ResourceManager.GetString("Miqote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Count:  的本地化字符串。
        /// </summary>
        public static string Mod_Count_colon {
            get {
                return ResourceManager.GetString("Mod_Count_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod Repos 的本地化字符串。
        /// </summary>
        public static string Mod_Repos {
            get {
                return ResourceManager.GetString("Mod_Repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model ID 的本地化字符串。
        /// </summary>
        public static string Model_ID {
            get {
                return ResourceManager.GetString("Model_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 modelchara_0.exd 的本地化字符串。
        /// </summary>
        public static string ModelCharaFile {
            get {
                return ResourceManager.GetString("ModelCharaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModelSearch 的本地化字符串。
        /// </summary>
        public static string ModelSearch {
            get {
                return ResourceManager.GetString("ModelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModList 的本地化字符串。
        /// </summary>
        public static string ModList {
            get {
                return ResourceManager.GetString("ModList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modlist Directory 的本地化字符串。
        /// </summary>
        public static string Modlist_Directory {
            get {
                return ResourceManager.GetString("Modlist_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modpack Creator 的本地化字符串。
        /// </summary>
        public static string Modpack_Creator {
            get {
                return ResourceManager.GetString("Modpack_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModPack Directory 的本地化字符串。
        /// </summary>
        public static string ModPack_Directory {
            get {
                return ResourceManager.GetString("ModPack_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModPack Importer 的本地化字符串。
        /// </summary>
        public static string ModPack_Importer {
            get {
                return ResourceManager.GetString("ModPack_Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModPack Name: 的本地化字符串。
        /// </summary>
        public static string ModPack_Name_colon {
            get {
                return ResourceManager.GetString("ModPack_Name_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tool will create a zipped TexTools Mod Pack (*.ttmp) file of the selected mods in the following directory: 的本地化字符串。
        /// </summary>
        public static string ModpackCreatorInfo {
            get {
                return ResourceManager.GetString("ModpackCreatorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following Mods will be installed. 的本地化字符串。
        /// </summary>
        public static string ModpackImporterInfo {
            get {
                return ResourceManager.GetString("ModpackImporterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster 的本地化字符串。
        /// </summary>
        public static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 b{0}.imc 的本地化字符串。
        /// </summary>
        public static string MonsterIMCFile {
            get {
                return ResourceManager.GetString("MonsterIMCFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/monster/m{0}/obj/body/b{1} 的本地化字符串。
        /// </summary>
        public static string MonsterIMCFolder {
            get {
                return ResourceManager.GetString("MonsterIMCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 m{0}b{1}.mdl 的本地化字符串。
        /// </summary>
        public static string MonsterMDLFile {
            get {
                return ResourceManager.GetString("MonsterMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/monster/m{0}/obj/body/b{1}/model 的本地化字符串。
        /// </summary>
        public static string MonsterMDLFolder {
            get {
                return ResourceManager.GetString("MonsterMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_m{0}b{1}_{2}.mtrl 的本地化字符串。
        /// </summary>
        public static string MonsterMtrlFile {
            get {
                return ResourceManager.GetString("MonsterMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/monster/m{0}/obj/body/b{1}/material/v 的本地化字符串。
        /// </summary>
        public static string MonsterMtrlFolder {
            get {
                return ResourceManager.GetString("MonsterMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 skl_m{0}b{1}.sklb 的本地化字符串。
        /// </summary>
        public static string MonsterSkelFile {
            get {
                return ResourceManager.GetString("MonsterSkelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/monster/m{0}/skeleton/base/b{1} 的本地化字符串。
        /// </summary>
        public static string MonsterSkelFolder {
            get {
                return ResourceManager.GetString("MonsterSkelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 23 的本地化字符串。
        /// </summary>
        public static string Mount_Category {
            get {
                return ResourceManager.GetString("Mount_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mount_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string MountFile {
            get {
                return ResourceManager.GetString("MountFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mounts 的本地化字符串。
        /// </summary>
        public static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neck 的本地化字符串。
        /// </summary>
        public static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nexus Mods 的本地化字符串。
        /// </summary>
        public static string NexusMods {
            get {
                return ResourceManager.GetString("NexusMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num 的本地化字符串。
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off Hand 的本地化字符串。
        /// </summary>
        public static string Off_Hand {
            get {
                return ResourceManager.GetString("Off_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Status 的本地化字符串。
        /// </summary>
        public static string OnlineStatus {
            get {
                return ResourceManager.GetString("OnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 onlinestatus_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string OnlineStatusEXD {
            get {
                return ResourceManager.GetString("OnlineStatusEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenCOLLADA 的本地化字符串。
        /// </summary>
        public static string OpenCollada {
            get {
                return ResourceManager.GetString("OpenCollada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part: 的本地化字符串。
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part Attributes: 的本地化字符串。
        /// </summary>
        public static string Part_Attributes {
            get {
                return ResourceManager.GetString("Part_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part 的本地化字符串。
        /// </summary>
        public static string Part2 {
            get {
                return ResourceManager.GetString("Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parts: 的本地化字符串。
        /// </summary>
        public static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pet_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string PetEXD {
            get {
                return ResourceManager.GetString("PetEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pets 的本地化字符串。
        /// </summary>
        public static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrettyKitty Emporium 的本地化字符串。
        /// </summary>
        public static string PKEmporium {
            get {
                return ResourceManager.GetString("PKEmporium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder-Egi 的本地化字符串。
        /// </summary>
        public static string Placeholder_Egi {
            get {
                return ResourceManager.GetString("Placeholder_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 placename_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Race 的本地化字符串。
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ramuh Egi 的本地化字符串。
        /// </summary>
        public static string Ramuh_Egi {
            get {
                return ResourceManager.GetString("Ramuh_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflection 的本地化字符串。
        /// </summary>
        public static string Reflection {
            get {
                return ResourceManager.GetString("Reflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rings 的本地化字符串。
        /// </summary>
        public static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rings_Left 的本地化字符串。
        /// </summary>
        public static string RingsLeft {
            get {
                return ResourceManager.GetString("RingsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roegadyn 的本地化字符串。
        /// </summary>
        public static string Roegadyn {
            get {
                return ResourceManager.GetString("Roegadyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rook Autoturret 的本地化字符串。
        /// </summary>
        public static string Rook_Autoturret {
            get {
                return ResourceManager.GetString("Rook_Autoturret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All DDS 的本地化字符串。
        /// </summary>
        public static string Save_All_DDS {
            get {
                return ResourceManager.GetString("Save_All_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Directory 的本地化字符串。
        /// </summary>
        public static string Save_Directory {
            get {
                return ResourceManager.GetString("Save_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search: 的本地化字符串。
        /// </summary>
        public static string Search_colon {
            get {
                return ResourceManager.GetString("Search_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Textures 的本地化字符串。
        /// </summary>
        public static string SearchBox {
            get {
                return ResourceManager.GetString("SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Active 的本地化字符串。
        /// </summary>
        public static string Select_Active {
            get {
                return ResourceManager.GetString("Select_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selene 的本地化字符串。
        /// </summary>
        public static string Selene {
            get {
                return ResourceManager.GetString("Selene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sephirot-Egi 的本地化字符串。
        /// </summary>
        public static string Sephirot_Egi {
            get {
                return ResourceManager.GetString("Sephirot_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string Size_colon {
            get {
                return ResourceManager.GetString("Size_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skin 的本地化字符串。
        /// </summary>
        public static string Skin {
            get {
                return ResourceManager.GetString("Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slot 的本地化字符串。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soul Crystal 的本地化字符串。
        /// </summary>
        public static string Soul_Crystal {
            get {
                return ResourceManager.GetString("Soul_Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specular 的本地化字符串。
        /// </summary>
        public static string Specular {
            get {
                return ResourceManager.GetString("Specular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 status_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string StatusExd {
            get {
                return ResourceManager.GetString("StatusExd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tail 的本地化字符串。
        /// </summary>
        public static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 c{0}t{1}_{2}.mdl 的本地化字符串。
        /// </summary>
        public static string TailMDLFile {
            get {
                return ResourceManager.GetString("TailMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/tail/t{1}/model 的本地化字符串。
        /// </summary>
        public static string TailMDLFolder {
            get {
                return ResourceManager.GetString("TailMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_c{0}t{1}_a.mtrl 的本地化字符串。
        /// </summary>
        public static string TailMtrlFile {
            get {
                return ResourceManager.GetString("TailMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/human/c{0}/obj/tail/t{1}/material 的本地化字符串。
        /// </summary>
        public static string TailMtrlFolder {
            get {
                return ResourceManager.GetString("TailMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D Import Options 的本地化字符串。
        /// </summary>
        public static string TD_Import_Options {
            get {
                return ResourceManager.GetString("TD_Import_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D Model 的本地化字符串。
        /// </summary>
        public static string TD_Model {
            get {
                return ResourceManager.GetString("TD_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture 的本地化字符串。
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Titan-Egi 的本地化字符串。
        /// </summary>
        public static string Titan_Egi {
            get {
                return ResourceManager.GetString("Titan_Egi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Size:  的本地化字符串。
        /// </summary>
        public static string Total_Size_colon {
            get {
                return ResourceManager.GetString("Total_Size_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translucency OFF 的本地化字符串。
        /// </summary>
        public static string Translucency_OFF {
            get {
                return ResourceManager.GetString("Translucency_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translucency ON 的本地化字符串。
        /// </summary>
        public static string Translucency_ON {
            get {
                return ResourceManager.GetString("Translucency_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparency 的本地化字符串。
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two Handed 的本地化字符串。
        /// </summary>
        public static string Two_Handed {
            get {
                return ResourceManager.GetString("Two_Handed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Icon Search 的本地化字符串。
        /// </summary>
        public static string UI_Icon_Search {
            get {
                return ResourceManager.GetString("UI_Icon_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 060000 的本地化字符串。
        /// </summary>
        public static string UIDat {
            get {
                return ResourceManager.GetString("UIDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.tex 的本地化字符串。
        /// </summary>
        public static string UIFile {
            get {
                return ResourceManager.GetString("UIFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update TEX 的本地化字符串。
        /// </summary>
        public static string Update_TEX {
            get {
                return ResourceManager.GetString("Update_TEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Original Bones 的本地化字符串。
        /// </summary>
        public static string UseOrignalBones {
            get {
                return ResourceManager.GetString("UseOrignalBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variant 的本地化字符串。
        /// </summary>
        public static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Viewer 的本地化字符串。
        /// </summary>
        public static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waist 的本地化字符串。
        /// </summary>
        public static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 b{0}.imc 的本地化字符串。
        /// </summary>
        public static string WeapIMCFile {
            get {
                return ResourceManager.GetString("WeapIMCFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/weapon/w{0}/obj/body/b{1} 的本地化字符串。
        /// </summary>
        public static string WeapIMCFolder {
            get {
                return ResourceManager.GetString("WeapIMCFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 w{0}b{1}.mdl 的本地化字符串。
        /// </summary>
        public static string WeapMDLFile {
            get {
                return ResourceManager.GetString("WeapMDLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/weapon/w{0}/obj/body/b{1}/model 的本地化字符串。
        /// </summary>
        public static string WeapMDLFolder {
            get {
                return ResourceManager.GetString("WeapMDLFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mt_w{0}b{1}_{2}.mtrl 的本地化字符串。
        /// </summary>
        public static string WeapMtrlFile {
            get {
                return ResourceManager.GetString("WeapMtrlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/weapon/w{0}/obj/body/b{1}/material/v 的本地化字符串。
        /// </summary>
        public static string WeapMtrlFolder {
            get {
                return ResourceManager.GetString("WeapMtrlFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon 的本地化字符串。
        /// </summary>
        public static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 skl_w{0}b{1}.sklb 的本地化字符串。
        /// </summary>
        public static string WeapSkelFile {
            get {
                return ResourceManager.GetString("WeapSkelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/weapon/w{0}/skeleton/base/b{1} 的本地化字符串。
        /// </summary>
        public static string WeapSkelFolder {
            get {
                return ResourceManager.GetString("WeapSkelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vw{0}.avfx 的本地化字符串。
        /// </summary>
        public static string WeapVFXFile {
            get {
                return ResourceManager.GetString("WeapVFXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 chara/weapon/w{0}/obj/body/b{1}/vfx/eff 的本地化字符串。
        /// </summary>
        public static string WeapVFXFolder {
            get {
                return ResourceManager.GetString("WeapVFXFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weather 的本地化字符串。
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 weather_0_{0}.exd 的本地化字符串。
        /// </summary>
        public static string WeatherEXD {
            get {
                return ResourceManager.GetString("WeatherEXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrists 的本地化字符串。
        /// </summary>
        public static string Wrists {
            get {
                return ResourceManager.GetString("Wrists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XIV Mod Archive 的本地化字符串。
        /// </summary>
        public static string XMArchive {
            get {
                return ResourceManager.GetString("XMArchive", resourceCulture);
            }
        }
    }
}
